from api.infrastructure.repositories.menus import DjangoORMMenusRepository
from api.infrastructure.repositories.usuario_menus import DjangoORMUsuarioMenusRepository
from api.infrastructure.repositories.usuarios import DjangoORMUsuariosRepository
from api.infrastructure.repositories.perfiles import DjangoORMPerfilRepository