# Generated by Django 3.1.7 on 2021-02-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('entrada', models.CharField(max_length=255, null=True)),
                ('ensalada', models.CharField(max_length=255, null=True)),
                ('plato_fondo', models.CharField(max_length=255, null=True)),
                ('postre', models.CharField(max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_menu', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
        migrations.AddField(
            model_name='menu',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
