from api.application.repositories.usuarios import UsuariosRepository
from api.application.repositories.menus import MenusRepository
from api.application.repositories.usuario_menus import UsuarioMenusRepository